version: '3'
services:
   backend:
    build: ./backend  
    ports:
     - "3000:3000"  
    depends_on:
     - db
    environment:
      - DB_HOST=db
      - DB_USER=root
      - DB_PASSWORD=rootpassword
      - DB_NAME=usersdb

   db:
    image: mysql:5.7
    environment:
      MYSQL_ROOT_PASSWORD: rootpassword  
      MYSQL_DATABASE: usersdb
    ports:
     - "3306:3306"  
    volumes:
     - db-dataa:/var/lib/mysql  

volumes:
    db-dataa:
      
